apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: devops
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: monta12345
  MYSQL_DATABASE: Student-Management
  MYSQL_USER: Student
  MYSQL_PASSWORD: pass12345

